# Generated by Django 4.2 on 2023-06-12 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ReservaModels",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome_do_pet",
                    models.CharField(max_length=50, verbose_name="Nome do pet"),
                ),
                ("telefone", models.CharField(max_length=50, verbose_name="Telefone")),
                ("data_da_reserva", models.DateField(verbose_name="Data de reserva")),
                (
                    "observacoes",
                    models.TextField(default="nulo", verbose_name="Observações"),
                ),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("veterinário", "Serviços veterinários"),
                            ("tosagem", "Tosagem"),
                            ("alimentacao", "Rações"),
                            ("limpeza_pet", "Banho Pet"),
                        ],
                        default="nulo",
                        max_length=50,
                        verbose_name="Categorias",
                    ),
                ),
                (
                    "enviado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Eviado em"),
                ),
                (
                    "auteracao",
                    models.DateTimeField(auto_now=True, verbose_name="Auterado em"),
                ),
            ],
        ),
    ]
