# Generated by Django 4.2 on 2023-06-17 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("basic", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reservamodels",
            options={
                "ordering": ["-data_da_reserva"],
                "verbose_name": "Formulário de reserva",
                "verbose_name_plural": "Fomulário de reserva",
            },
        ),
    ]
