# Generated by Django 4.2 on 2023-06-18 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("basic", "0002_alter_reservamodels_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservamodels",
            name="lido",
            field=models.BooleanField(default=False, verbose_name="Lido"),
        ),
    ]
