# Generated by Django 4.2 on 2023-06-18 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("basic", "0003_reservamodels_lido"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reservamodels",
            options={
                "ordering": ["-data_da_reserva"],
                "verbose_name": "Formulário de reserva",
                "verbose_name_plural": "Fomulários de reservas",
            },
        ),
    ]
